demo/src/main.ts, demo/src/options/options25.html, demo/src/options/options25.ts, demo/src/style.scss, lib/src/MultipleSelectInstance.ts, lib/src/styles/_variables.scss, lib/src/styles/multiple-select.scss
- prior to this PR the "Select All" was part of the ul > list and was being scrolled when scrolling up & down, however with this PR it was moved outside the list and on top of the list without it being scrollable
- also fix active nav not being changed when using browser history backward/forward
=> chore: move Select All as div on top and outside of ul list

README.md, demo/src/app-routing.ts, demo/src/options/options29.html, demo/src/options/options29.ts, demo/src/options/options30.html, demo/src/options/options30.ts, lib/build-watch.mjs, lib/package.json, lib/src/MultipleSelectInstance.ts, lib/src/constants.ts, lib/src/interfaces/multipleSelectOption.interface.ts, lib/src/styles/multiple-select.scss, lib/src/utils/domUtils.ts, package.json, pnpm-lock.yaml
=> feat: auto-adjust height by available space & width by text content

demo/src/options/options02.html, lib/src/MultipleSelectInstance.ts, lib/src/styles/_variables.scss, lib/src/styles/multiple-select.scss
=> fix: single select radio should work with empty label select option

demo/src/main.ts, lib/src/MultipleSelectInstance.ts, lib/src/utils/domUtils.ts
- also add 3rd argument for a parent element to optionally append to
=> fix: create DOM element util should spread element props

lib/package.json, lib/vite.config.ts, pnpm-lock.yaml
- some options got renamed, in our case only `outputDir` -> `outDir` is affecting our project
=> chore(deps): upgrade `vite-plugin-dts` to new major v3.0

lib/src/MultipleSelectInstance.ts
=> fix: select option should compare full value not substring, fix #115

lib/package.json
- should hopefully fix issue #123
=> fix: remove type module to support non-ESM, fixes #123

lib/src/locales/all-locales-index.ts, lib/src/locales/multiple-select-ja-JP.ts
- from ms-select PR https://github.com/wenzhixin/multiple-select/pull/608
=> feat: added locale ja-JP

lib/src/MultipleSelectInstance.ts
- as per original ms-select lib PR https://github.com/wenzhixin/multiple-select/pull/609
=> fix: updated onFilter event parameter to original search

demo/src/app-routing.ts, demo/src/examples/example10.ts, demo/src/options/options34.html, demo/src/options/options34.ts, lib/src/MultipleSelectInstance.ts, lib/src/interfaces/multipleSelectOption.interface.ts, lib/src/styles/multiple-select.scss, playwright/e2e/options34.spec.ts
=> feat: add `showSearchClear` option to clear search input

lib/package.json
- hopefully get better result when checking exports in https://arethetypeswrong.github.io/?p=multiple-select-vanilla
=> fix: adjust types & exports for all bundler

packages/demo/src/app-routing.ts, packages/demo/src/examples/example15.html, packages/demo/src/examples/example15.scss, packages/demo/src/examples/example15.ts, packages/demo/src/methods/methods02.html, packages/demo/src/methods/methods02.ts, packages/multiple-select-vanilla/src/MultipleSelectInstance.ts, packages/multiple-select-vanilla/src/interfaces/multipleSelectOption.interface.ts, packages/multiple-select-vanilla/src/styles/_variables.scss, packages/multiple-select-vanilla/src/styles/multiple-select.scss, playwright/e2e/example15.spec.ts, playwright/e2e/methods02.spec.ts
- add a `darkMode` option, user can also change it at any time dynamically via `refreshOptions()`
- see new [Dark Mode](https://ghiscoding.github.io/multiple-select-vanilla/#/example15) example
=> feat: add Dark Mode option

packages/demo/src/app-routing.ts, packages/demo/src/options/options37.html, packages/demo/src/options/options37.ts, packages/multiple-select-vanilla/src/MultipleSelectInstance.ts, packages/multiple-select-vanilla/src/constants.ts, packages/multiple-select-vanilla/src/interfaces/multipleSelectOption.interface.ts, playwright/e2e/methods01.spec.ts, playwright/e2e/options37.spec.ts
- for whatever reason, the user might want to disable the feature, hence this new option
=> feat: add `navigationHighlight` to optionally disable built-in feature

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts, packages/multiple-select-vanilla/src/styles/multiple-select.scss, playwright/e2e/example02.spec.ts, playwright/e2e/methods02.spec.ts, playwright/e2e/methods06.spec.ts
- on the new implementation and prior to this PR, I was creating the icon container for the SVG icon even when it wasn't needed.
=> fix: only add icon container element when actually used

playwright/e2e/options25.spec.ts
- adding missing tests for last commit
=> chore: add E2E tests for last Tab/Shift+Tab commit

packages/demo/src/examples/example16.ts, packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
- infinite scroll should also work with small list even it doesn't have a scroll
=> fix: infinite scroll with arrow navigation should work with short list

packages/multiple-select-vanilla/src/styles/_variables.scss, packages/multiple-select-vanilla/src/styles/multiple-select.scss
- add a CSS/SASS variable instead to make it customizable
=> fix: remove column gap and leave it to be customizable by user

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
- also resolve a Promise for open() method to know when it finished
=> fix: Escape key should always close drop

.github/workflows/main.yml, README.md, packages/demo/src/getting-started.html, packages/demo/vite.config.mts, packages/multiple-select-vanilla/build-prod.mjs, packages/multiple-select-vanilla/clone-dts.mjs, packages/multiple-select-vanilla/package.json
- it's time to drop CommonJS and go full ESM-Only
=> feat!: build as ESM-Only, drop CJS

packages/demo/src/options/options42.html, packages/demo/src/options/options42.ts, packages/multiple-select-vanilla/src/MultipleSelectInstance.ts, packages/multiple-select-vanilla/src/styles/_variables.scss, packages/multiple-select-vanilla/src/styles/multiple-select.scss, playwright/e2e/options42.spec.ts
found a few small issues after giving a try to lazy load data in my other datagrid lib
=> fix: couple of issues related to lazy loading

packages/multiple-select-vanilla/src/index.ts, packages/multiple-select-vanilla/src/utils/domUtils.ts, packages/multiple-select-vanilla/src/utils/utils.ts
- remove some functions that aren't used anywhere
=> chore: remove unused functions

.github/renovate.json5, package.json, pnpm-lock.yaml
- also change Renovate schedule to run every 3 months
=> chore(deps): upgrade `rimraf` and `npm-run-all2` to new major
