ghiscoding/multiple-select-vanilla

README.md
demo/package.json
demo/src/app-routing.ts
demo/src/options/options30.html
demo/src/options/options30.ts
demo/src/options/options31.html
demo/src/options/options31.ts
lib/build-watch.mjs
lib/package.json
lib/src/MultipleSelectInstance.ts
lib/src/constants.ts
lib/src/interfaces/multipleSelectOption.interface.ts
lib/src/utils/utils.ts
package.json
pnpm-lock.yaml

- this new option can be useful to display option value as label (ie: value "1" instead of "January")

feat: add new `useSelectOptionLabel` option

---

README.md
demo/package.json
demo/src/app-routing.ts
demo/src/examples/example12.html
demo/src/examples/example12.scss
demo/src/examples/example12.ts
lib/package.json
lib/src/styles/_variables.scss
package.json
pnpm-lock.yaml

feat: provide demo with Font-Awesome checkbox/radio icons

---

demo/src/examples/example09.ts
demo/src/i18n/i18n.ts
lib/src/MultipleSelectInstance.ts
lib/src/interfaces/multipleSelectOption.interface.ts

- this brings back the text patterns that were available in multiple-select v1.2.1, however some of these options have different names in comparison to the previous version, they now all have the "text" suffix

feat: add string pattern options as alternative to override text formats

---

lib/src/MultipleSelectInstance.ts
playwright/e2e/methods05.spec.ts

- in the original ms-select, the body click was being triggered prior to the open() method but that is inversed in our new lib with vanilla JS, so in order to have the same lifecycle as the original, we can simply add a single CPU cycle delay. This delay arg could also be used by the users for other reasons
- the `open()` method which this PR fixes is demoed in [methods 05](https://ghiscoding.github.io/multiple-select-vanilla/#/methods05) demo

fix: calling open() method multiple times should keep drop (re)open

---

demo/src/methods/methods06.html
demo/src/methods/methods07.html
demo/src/methods/methods08.html
playwright/e2e/events.spec.ts
playwright/e2e/i18n.spec.ts
playwright/e2e/methods01.spec.ts
playwright/e2e/methods02.spec.ts
playwright/e2e/methods03.spec.ts
playwright/e2e/methods04.spec.ts
playwright/e2e/methods06.spec.ts
playwright/e2e/methods07.spec.ts
playwright/e2e/methods08.spec.ts
playwright/e2e/methods09.spec.ts
playwright/e2e/methods10.spec.ts
playwright/e2e/methods11.spec.ts

- this PR adds E2E tests for all demos

chore: add Playwright full test coverage

---

lib/src/MultipleSelectInstance.ts

some methods aren't supported in Salesforce for unknown reasons and it throws some errors like "append function does not exist"

fix: replace some DOM Element method not supported in Salesforce

---

demo/src/options/options27.html
demo/src/options/options27.ts
lib/src/MultipleSelectInstance.ts
lib/src/utils/domUtils.ts
playwright/e2e/options27.spec.ts

- when using `data` option to provide a collection of data, we should only render when `renderOptionLabelAsHtml` or `useSelectOptionLabelToHtml` is enabled, otherwise we should display same text input (html encoded instead of being rendered as html)

fix: data collection shouldn't render label as html by default

---

lib/package.json

- when defining the old CJS `main` and `module`, these properties should come after `exports` (new ESM prop) so that newer Node will try `exports` first and not try fallback first, while for old Node it will automatically use the fallbacks since `exports` won't work, see this TypeScript for more info (https://www.typescriptlang.org/docs/handbook/esm-node.html)

fix: CJS fallbacks should be at the end not at beginning

---

lib/src/MultipleSelectInstance.ts
lib/src/constants.ts
lib/src/interfaces/multipleSelectOption.interface.ts

- Use `onBeforeClick` to prevent the click event, as per original ms-select lib PR https://github.com/wenzhixin/multiple-select/pull/610

feat: added `onBeforeClick` event

---

demo/src/main.ts
lib/src/MultipleSelectInstance.ts
lib/src/services/virtual-scroll.ts
lib/src/utils/utils.ts

- also replace all MultipleSelect `innerHTML` except for when renderAsHtml is enabled

feat: VirtualScroll replace all html strings to pure HTML elements

---

demo/src/options/options26.html
demo/src/options/options26.ts
lib/src/MultipleSelectInstance.ts
lib/src/interfaces/multipleSelectOption.interface.ts
playwright/e2e/options26.spec.ts

deprecate `styler` in favor of a new `cssStyler` which have better typing support and can use direct assignment. The previous use of `innerHTML` made it easier to use `styler` but now that we switched to pure HTML Element, it is better to use `CSSStyleDeclaration` props. Since we moved to pure HTML Element, the `styler` is requiring a bit more logic, since we now have to do string split of semicolon `;`, then use `toCamelCase` for CSS assignment... which is why the new `cssStyler` is better since we can simply loop through all styling props and assign directly
```ts
styler: (row: OptionRowData | OptGroupRowData) => {
if (row?.type === 'optgroup') {
return 'color: #777; font-weight: normal;';
}
}
```
```ts
styler: (row: OptionRowData | OptGroupRowData) => {
if (row?.type === 'optgroup') { …
```

feat: add `cssStyler` option to use typed CSSStyleDeclaration props

---

demo/index.html
demo/package.json
demo/src/main.ts
pnpm-lock.yaml

- last few PRs made the lib more CSP compliant, this PR simply adds the CSP meta tag to the online demo
- note however that `style-src` is using `unsafe-inline` and should be adressed in the future but I think the blocker is mainly coming from Vite and might be fix soon by Vite's PR 14653

chore: add CSP (Content Security Policy) to demo

---

lib/src/MultipleSelectInstance.ts
lib/src/interfaces/interfaces.ts
lib/src/services/virtual-scroll.ts
lib/src/utils/domUtils.ts

- the previous migration to plain/pure HTML Element was great for CSP but keeping a large array of HTMLElement can consume a lot of memory and is not the fastest especially when dealing with large dataset (thousand of items), what we can do instead of keep a minimal html struct (html tag name and the props/attrs that we are interested only), so whenever we need to recreate the list of element it is much quicker to create basic struct than it is to create thousand of HTMLElement and it consumes a lot less memory.
- perf seems to double when using html struct instead of plain HTMLElement
- the perf comparison was mostly done in the [Large Dataset](https://ghiscoding.github.io/multiple-select-vanilla/#/example10) example which is where this PR will have the biggest impact

perf: use array of html struct instead of plain HTML Element

---

lib/src/MultipleSelectInstance.ts

- when we are filtering, the previous code was calling `initListItems()` and then `updateSelected()` which both recreate the rows list, there's no need to do it twice when we can simply pass it from the 1st pass to the 2nd method for other transformation

perf: don't recreate items list twice while filtering

---

lib/src/MultipleSelectInstance.ts
lib/src/utils/domUtils.ts
lib/src/utils/utils.ts

- define html struct prop even with null props, we'll now remove null props before calling createDomElement to avoid creating empty HTML class/title/...

chore: code cleanup & simpler html struct object

---

lib/src/utils/domUtils.ts
lib/src/utils/utils.ts

- last version refactoring removed all empty props & attributes when creating DOM element but we should never remove input `value` prop even when it is null or empty

fix: input checkbox value should always be included even when null

---

.github/workflows/main.yml

- caching seems to be a problem, very often the PR looks good but issue were resurfacing after merging the PR and that seem to be a caching issue, hopefully this fixes it
- use same config as Slickgrid-Universal project
- add Node 20 on top of Node 18 environment to test against

chore: change CI workflow to avoid caching issues

---

lib/package.json
pnpm-lock.yaml

- we need to move `@types/trusted-types` as a project dependecy instead of dev deps because we do use it in our interface and that came out as an issue from another user

fix: `@types/trusted-types` should be lib dependency

---

package.json
pnpm-lock.yaml

- use `servor` to serve a Prod build

chore: serve prod build to run E2E tests without using Vite dev mode

---

lib/build-prod.mjs
lib/build-watch.mjs
lib/package.json

- however to keep using `.js` for both builds, it requires us to separate files, since we prefer ESM, we will only add `-cjs` to 2 folders (`locales-cjs` and `browser-cjs`)
The reason is because of the new result from [Are the Types wrong?](https://arethetypeswrong.github.io/?p=multiple-select-vanilla%401.0.1) website, the hope is to fix this masquerade which we didn't have before 1.0 release

fix: revert to using `.js` for both CJS/ESM

---

lib/src/MultipleSelectInstance.ts
lib/src/services/binding-event.service.ts
lib/src/utils/domUtils.ts
playwright/e2e/example02.spec.ts
playwright/e2e/example03.spec.ts

- add tabIndex on every list item and select-all checkbox so that we can use up/down arrows to focus on next or previous item.
- divider will be skipped and ignored
- using Enter or Space key will select/unselect the input checkbox of the current item

feat: add tabindex to list item to control up/down arrow direction

---

lib/src/MultipleSelectInstance.ts

fix: add `aria-expanded` on ms-drop element, fixes #178

---

lib/src/MultipleSelectInstance.ts

- I'm not sure if it's related or not but this Angular-Slickgrid issue came up with this error so I wonder if this could help to use older code that is more compatibile
```ts
Function.prototype.toString requires that 'this' be a Function at Boolean.toString
```
https://github.com/ghiscoding/Angular-Slickgrid/issues/1334

fix: don't use `Boolean()` for compatibility

---

packages/demo/src/options/options35.html
packages/demo/src/options/options35.ts
packages/multiple-select-vanilla/src/styles/_variables.scss
packages/multiple-select-vanilla/src/styles/multiple-select.scss
playwright/e2e/options35.spec.ts

- adding a 2nd Select since we should  also have E2E tests for our built-in parser which uses `str.normalize('NFD')`

chore: add demo for built-in diacritic parser [refresh gh-pages]

---

packages/multiple-select-vanilla/package.json

for source map to work properly, the `src/` folder must be included while running npm publish

fix(npm): publish src folder for source maps

---

packages/demo/src/examples/example10.html
packages/demo/src/examples/example10.ts
packages/demo/src/main.html
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/utils/domUtils.ts
playwright/e2e/example10.spec.ts

- fixes issue #203
- the issue was only showing up when the user had any of the render HTML option(s) enabled to render label text as HTML
- this PR adds an extra select to Example 10 (Large Select) with HTML rendering in order to test the bug fix and also have E2E tests covering it as well (as shown below)

fix: Virtual Scroll not working on large dataset w/HTML render enabled, fixes #203

---

.github/workflows/main.yml
packages/demo/src/app-routing.ts
packages/demo/src/examples/example10.html
packages/demo/src/style.scss
packages/demo/vite.config.mts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/services/virtual-scroll.ts
packages/multiple-select-vanilla/src/styles/_variables.scss
packages/multiple-select-vanilla/src/styles/multiple-select.scss
playwright/e2e/events.spec.ts
playwright/e2e/example02.spec.ts
playwright/e2e/example03.spec.ts
playwright/e2e/example04.spec.ts
playwright/e2e/example07.spec.ts
playwright/e2e/example08.spec.ts
playwright/e2e/example11.spec.ts
playwright/e2e/example12.spec.ts
playwright/e2e/i18n.spec.ts
playwright/e2e/options02.spec.ts
playwright/e2e/options17.spec.ts
playwright/e2e/options18.spec.ts
playwright/e2e/options19.spec.ts
playwright/e2e/options22.spec.ts
playwright/e2e/options25.spec.ts
playwright/e2e/options33.spec.ts
playwright/e2e/options34.spec.ts
playwright/e2e/options35.spec.ts

- fixes #206
- previous tabIndex implementation (in PR #176) required to use arrow to go up/down the list OR use filter (when enabled) BUT not both at the same time, this new implementation is more UX friendly and is typically what most user will want which is to keep filter in focus but also allow to use up/down arrow at the same time
- tabIndex has many drawbacks, mostly related to the fact that you can only work with current focused item, but on the other hand when switching to highlight, we can keep focus on the filter while still using the arrow to go up/down the list of select options
- using mouse hover will also update the current option highlight to mouse position
- also change selection and checkbox to use default primary color
- considering this as a breaking (major) change …

feat!: replace arrow up/down direction tabIndex by highlight, fix #206

---

.gitignore
.vscode/settings.json
README.md
packages/demo/src/examples/example09.html
packages/demo/src/examples/example09.ts
packages/demo/src/i18n/i18n.ts
packages/multiple-select-vanilla/index.d.ts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/interfaces/index.ts
packages/multiple-select-vanilla/src/interfaces/interfaces.ts
packages/multiple-select-vanilla/src/interfaces/locale.interface.ts
packages/multiple-select-vanilla/src/interfaces/multipleSelectOption.interface.ts
packages/multiple-select-vanilla/src/locales/multiple-select-cz-CS.ts
packages/multiple-select-vanilla/src/locales/multiple-select-da-DK.ts
packages/multiple-select-vanilla/src/locales/multiple-select-en-US.ts
packages/multiple-select-vanilla/src/locales/multiple-select-es-ES.ts
packages/multiple-select-vanilla/src/locales/multiple-select-fr-FR.ts
packages/multiple-select-vanilla/src/locales/multiple-select-hu-HU.ts
packages/multiple-select-vanilla/src/locales/multiple-select-it-IT.ts
packages/multiple-select-vanilla/src/locales/multiple-select-ja-JP.ts
packages/multiple-select-vanilla/src/locales/multiple-select-pt-BR.ts
packages/multiple-select-vanilla/src/locales/multiple-select-ru-RU.ts
packages/multiple-select-vanilla/src/locales/multiple-select-vi-VN.ts
packages/multiple-select-vanilla/src/locales/multiple-select-zh-CN.ts
packages/multiple-select-vanilla/src/locales/multiple-select-zh-TW.ts
playwright/e2e/example09.spec.ts

- allow to import a single Locale via named imports
- for example:
```ts
import { Spanish } from 'multiple-select-vanilla/dist/locales/multiple-select-es-ES';
multipleSelect('#select', { locale: Spanish });
```
- also restrict the acceptable Locale key that can be provided to `locale`, for example:
- `{ locale: 'ja-JP' }` is valid 
- `{ locale: 'unknown' }` is invalid

feat!: export Locale as named exports

---

packages/demo/src/app-routing.ts
packages/demo/src/options/options36.html
packages/demo/src/options/options36.ts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/interfaces/multipleSelectOption.interface.ts
packages/multiple-select-vanilla/src/styles/_variables.scss
packages/multiple-select-vanilla/src/styles/multiple-select.scss
playwright/e2e/methods01.spec.ts
playwright/e2e/options36.spec.ts

- when reaching the end of the list, it will automatically reset it back to the top of the list
- the scroll can also be activated by using arrow down (highlight) to scroll 1 item at a time
- this is not to be confused with Virtual Scroll which is similar but only renders a subset of large collection until we reach the end at which point it will stop, however the infinite scroll never stops (at least not until the user stops scrolling)
- **note:** it only works while scrolling down **not** scrolling up

feat: add new option `infiniteScroll` auto-scroll back to top

---

packages/demo/src/examples/example10.html
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/constants.ts
packages/multiple-select-vanilla/src/interfaces/multipleSelectOption.interface.ts
playwright/e2e/methods01.spec.ts

- prior to this PR, the Virtual Scroll was always enabled and always rendering a subset of the list, around ~200 rows, but for whatever reason. The user might want to disable the Virtual Scroll entirely (for example if the list is 220 items then maybe v-scroll isn't necessary?)

feat: add `virtualScroll` option that could be disabled

---

.vscode/settings.json
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
playwright/e2e/options35.spec.ts

- opening the drop should move highlight to next available option but only on the initial opening, meaning that if we close and reopen the drop then it should keep its highlight index. Prior to this PR, closing/reopening multiple times was moving the highlight down by 1 option every time which is wrong

fix: opening drop should focus on next available option only initially

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts

- I was a little bit surprised about this but on certain platforms (mainly Salesforce in my case), the `role` attributes might completely stripped out of the final DOM template. So the DOM query I was using for arrow highlight navigation wasn't working at all in Salesforce. So removing `[role]` from the query selector is enough to get it working, however I'll add `li[datakey]` to get it working in Salesforce but still keep it focused to our expected list of elements to query for the arrow navigation to work

fix: query DOM element without role for cross-platform compatibility

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/styles/multiple-select.scss

- rotate/flip icon vertically when drop is open
- rename chevron-down icon to caret just to make it simpler and keep same name as before

fix: flip icon vertically when select drop is open

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
playwright/e2e/example15.spec.ts
playwright/e2e/options24.spec.ts
playwright/e2e/options38.spec.ts

fix: when using `showClear`, don't show btn unless having selection

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts

- when using arrow keys to change navigation highlight, it triggers couple of cascading events (1. onScroll event => 2. onMouseOver event). The onMouseOver has the side effect of changing the highlight to current mouse position, so that indirectly affected the arrow navigation since instead of staying at the bottom end, it was always resetting to mouse position (as shown in animated gif below). To counter this problem, we can save the last know mouse position and compare it inside the mouseover, if the position is exactly the same then we know that we're not using the mouse but we are actually using arrow navigation (so we skip mouseover exec)
this PR fixes the issue observed below (when the mouse is over the options list)

fix: nav highlight shouldn't follow mouse pos when using nav arrows

---

packages/demo/src/events/events.ts
packages/demo/src/options/options34.ts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/constants.ts
packages/multiple-select-vanilla/src/interfaces/multipleSelectOption.interface.ts
playwright/e2e/events.spec.ts

- we already have `onClear` event on the select button, but we should also add `onFilterClear` to be associated to the input filter

feat: add new event `onFilterClear` missing

---

packages/demo/src/options/options36.ts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/services/virtual-scroll.ts
playwright/e2e/options36.spec.ts

- there was an event leak for the Virtual-Scroll which had the side effect of duplicating the scroll event everytime we were filtering, this indirectly caused weird behavior with the scroll and also items being skipped. I found the leak via the browser by investigating the events attached to the ul list element
as shown below, every time a filter is being entered a scroll event was being added

fix: vscroll event mem leak causing unexpected behavior after filtering

---

packages/demo/src/examples/example09.html
packages/multiple-select-vanilla/src/interfaces/locale.interface.ts
packages/multiple-select-vanilla/src/locales/all-locales-index.ts
packages/multiple-select-vanilla/src/locales/multiple-select-de-DE.ts

I've added a locale for german language. Example did work as expected.

Added German locale

---

packages/multiple-select-vanilla/build-prod.mjs
packages/multiple-select-vanilla/package.json
packages/multiple-select-vanilla/tsup.config.ts
pnpm-lock.yaml

- we'll use `tsup` to create entries for CJS and ESM, however I'll keep using `esbuild` and `tsc` to bundle the rest which are all the locales and the IIFE build as well. We'll keep this until our next major which will drop CJS and we can go back to previous esbuild only approach
- also add [`@arethetypeswrong/cli`](https://www.npmjs.com/package/@arethetypeswrong/cli) to properly test hybrid CJS/ESM with Types and all package `exports`
- the hybrid approach is finally all good now

fix: full CJS/ESM hybrid support with tsup

---

packages/multiple-select-vanilla/src/styles/multiple-select.scss

in a previous commit b0e5d4d that fixed a typo introduced in PR #308, it actually only fixed the typo but in reality the typo was caused by a search & replace text and the `div.ms-icon-x` ended up dropping the `div.`, so we should probably add the div selector back

fix: add missing div selector in previous CSS class name typo

---

packages/demo/package.json
packages/demo/vite.config.mts
pnpm-lock.yaml

- Vite 6 made SASS modern-compiler the default so we can remove unnecessary option

chore: upgrade to Vite 6 and remove modern compiler

---

packages/demo/src/app-routing.ts
packages/demo/src/options/options40.html
packages/demo/src/options/options41.html
packages/demo/src/options/options41.ts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/models/multipleSelectOption.interface.ts
playwright/e2e/options40.spec.ts
playwright/e2e/options41.spec.ts

fixes #355
following the issue [comment](https://github.com/ghiscoding/multiple-select-vanilla/issues/355#issuecomment-2839020802), to pre-sort data before rendering the select dropdown

feat: add new `preSort` callback option, fixes #355

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts

- fixes an issue caught in datagrid unit tests, make sure that the drop list element isn't null before calling any functions on it

fix: make sure select drop list isn't null when adjusting drop width

---

packages/demo/src/events/events.ts
packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/constants.ts
packages/multiple-select-vanilla/src/models/multipleSelectOption.interface.ts
playwright/e2e/events.spec.ts

fixes #372
- Fires when any option/group selections changes.
- This event is triggered at the same time as any of these 4 events are being triggered: 
- `onCheckAll`
- `onUncheckAll`
- `onClick`
- `onOptgroupClick`
- the event uses this interface:
- `onChange: ({ eventName: string; item?: ClickedGroup | ClickedOption; selection: { labels: string[]; values: any[] } }) => void`
- the `eventName` will be 1 of the 4 event names shown above

feat: add `onChange` event whenever a selection changes, fix #372

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/models/multipleSelectOption.interface.ts
playwright/e2e/options25.spec.ts
playwright/e2e/options34.spec.ts
playwright/e2e/options43.spec.ts

- when multiple select is enabled and "OK" button is shown, it should take 2x Tab keys pressed to close the drop
1. focus on "OK" button
2. close drop
- fix some more issues after testing it more thoroughly in Slickgrid-Universal, there were some event conflicts since previous code had 2 listeners on the same drop element

fix: when `closeOnTab` w/OK button, it should take 2 Tabs to close

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts

- calling `event.composePath()` in a Salesforce environment with LWC and the locker API throws with an error: "Illegal Invocation" or "function does not exists"

fix: `event.composePath()` throws in Salesforce environment

---

packages/multiple-select-vanilla/tsconfig.json

there's no need to keep `sourceMap` if we're already using `declarationMap`, this will help decrease the shipped build size a little more

fix: use only TS declaration maps

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts

Any of these options `minWidth, maxWidth, width, dropWidth` should assign the option to the CSS style on the drop element. Note that the `dropWidth` is of course a custom option to assign as the drop `width` CSS style

fix: any min/max width options should be applied to drop CSS style

---

package.json
packages/multiple-select-vanilla/package.json
pnpm-lock.yaml

- I created my own [remove-glob](https://www.npmjs.com/package/remove-glob) which is 14x smaller than `rimraf` while still providing glob patterns (`premove` is a much better alternative when glob aren't necessary though).

chore(deps): use `remove-glob` instead of `rimraf`

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/styles/_variables.scss
packages/multiple-select-vanilla/src/styles/multiple-select.scss

properly adjust drop position underneath the select container by correctly using the container position and its height but only after it's rendered so that we have all the correct height and offset

fix: properly adjust drop position only after rendering

---

packages/multiple-select-vanilla/src/MultipleSelectInstance.ts
packages/multiple-select-vanilla/src/utils/domUtils.ts
packages/multiple-select-vanilla/src/utils/utils.ts

fixes #417
internal `applyAsTextOrHtmlWhenEnabled()` function should html decode value before passing them to `textContent`

fix: assigning text to `textContent` should be html decoded, fixes #417
